---
- name: "HIGH | V-234701 | PATCH | Chrome must be configured to allow only TLS."
  win_regedit:
      path: HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome
      value: SSLVersionMin
      data: 'tls1.2'
      type: dword
  when:
      - DTBC-0056
  tags:
    - DTBC-0056
    - cat1
    - CCI-002450
    - SRG-APP-000416
    - SV-234701r615937_rule
    - V-234701 
