---
- name: "LOW | V-221599 | PATCH | Chrome development tools must be disabled."
  win_regedit:
      path: HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome
      value: DeveloperToolsAvailability
      data: 2
      type: dword
  when:
    - DTBC-0068
  tags:
    - cat3
    - low
    - SRG-APP-000266
    - V-221599
    - SV-221599r615937_rule
    - DTBC-0068
    - patch

